Tecnativa/doodba-copier-template

- README.md
- copier.yml
Calling it with `python3 -m` makes it run in the same venv as copier itself.
Copier doesn't depend on invoke, and it could be installed isolated with `pipx` or similar tools, where invoke wouldn't be available. OTOH invoke itself could be installed with `pipx`, so it's better to just use the binary.
It has the con that in some distros `invoke` will be the py2 version. I warn about the binary name in the README.
> Use invoke binary

- copier.yml
- tests/conftest.py
- tests/test_transition_to_copier.py
Dependency files should be ignored if present; we don't want to alter them if user has modified them.
> Respect dependency files

- .github/workflows/automerge.yml
Reverts Tecnativa/doodba-copier-template#4 due to https://github.com/pascalgn/automerge-action/issues/56 making that label disappear from repo.
> Revert "Autoremove automerge label"

- .pre-commit-config.yaml.jinja
- tests/default_settings/v10.0/.pre-commit-config.yaml
- tests/default_settings/v11.0/.pre-commit-config.yaml
- tests/default_settings/v12.0/.pre-commit-config.yaml
- tests/default_settings/v13.0/.pre-commit-config.yaml
- tests/default_settings/v7.0/.pre-commit-config.yaml
- tests/default_settings/v8.0/.pre-commit-config.yaml
- tests/default_settings/v9.0/.pre-commit-config.yaml
Prettier 2 supports plugins, so it's better than using a random external repo.
Follows https://github.com/OCA/maintainer-quality-tools/pull/655#discussion_r399971845.
Also update some other hooks and MQT.
> Update pre-commit to Prettier 2

- copier.yml
- prod.yaml.jinja
- test.yaml.jinja
- tests/default_settings/v10.0/prod.yaml
- tests/default_settings/v10.0/test.yaml
- tests/default_settings/v11.0/prod.yaml
- tests/default_settings/v11.0/test.yaml
- tests/default_settings/v12.0/prod.yaml
- tests/default_settings/v12.0/test.yaml
- tests/default_settings/v13.0/prod.yaml
- tests/default_settings/v13.0/test.yaml
- tests/default_settings/v7.0/prod.yaml
- tests/default_settings/v7.0/test.yaml
- tests/default_settings/v8.0/prod.yaml
- tests/default_settings/v8.0/test.yaml
- tests/default_settings/v9.0/prod.yaml
- tests/default_settings/v9.0/test.yaml
- tests/test_default_settings.py
This will finally finish Tecnativa/doodba-scaffolding#67 by adding suport for Traefik 2.x and including a workaround for containous/traefik#5134 that should allow us to have 1 test and 1 prod instances together in the same machine.
Traefik 2 support is still experimental so use at your own risk. No docs yet, to emphasize that.
@Tecnativa TT21776
> Add traefik 2 support

- .pylintrc-mandatory.jinja
- .pylintrc.jinja
- copier.yml
- tests/default_settings/v10.0/.copier-answers.yml
- tests/default_settings/v10.0/.pylintrc
- tests/default_settings/v10.0/.pylintrc-mandatory
- tests/default_settings/v11.0/.copier-answers.yml
- tests/default_settings/v11.0/.pylintrc
- tests/default_settings/v11.0/.pylintrc-mandatory
- tests/default_settings/v12.0/.copier-answers.yml
- tests/default_settings/v12.0/.pylintrc
- tests/default_settings/v12.0/.pylintrc-mandatory
- tests/default_settings/v13.0/.copier-answers.yml
- tests/default_settings/v13.0/.pylintrc
- tests/default_settings/v13.0/.pylintrc-mandatory
- tests/default_settings/v7.0/.copier-answers.yml
- tests/default_settings/v7.0/.pylintrc
- tests/default_settings/v7.0/.pylintrc-mandatory
- tests/default_settings/v8.0/.copier-answers.yml
- tests/default_settings/v8.0/.pylintrc
- tests/default_settings/v8.0/.pylintrc-mandatory
- tests/default_settings/v9.0/.copier-answers.yml
- tests/default_settings/v9.0/.pylintrc
- tests/default_settings/v9.0/.pylintrc-mandatory
- tests/good_diffs/.pylintrc-mandatory.diff
- tests/good_diffs/.pylintrc.diff
- tests/test_nitpicking.py
You could have in your private modules you bought through the apps store. These modules could have `description` keys, and you could be no author there. These modules could have any license you want, or none since they belong to your project, which already has a license.
So, these things are now just warnings.
Also, not having OCA as author is almost *never* an error here, so that's changed for your own author, which is asked when copying.
> Use custom pylint templates

- docs/scaffolding2copier.sh
- migrations.py
When using copier >= 3.0.5 (and you should use that), migrating from doodba-scaffolding skipped `.editorconfig` migration.
Instead of fixing it in doodba-scaffolding, which is today archived, I prefer to fix it here.
At the same time, the `scaffolding2copier` script gets the latest update.
@Tecnativa TT20357 TT20739 @chienandalu
> Modernize transition

- poetry.lock
- prod.yaml.jinja
- pyproject.toml
- tasks.py
- test.yaml.jinja
- tests/default_settings/v10.0/prod.yaml
- tests/default_settings/v10.0/test.yaml
- tests/default_settings/v11.0/prod.yaml
- tests/default_settings/v11.0/test.yaml
- tests/default_settings/v12.0/prod.yaml
- tests/default_settings/v12.0/test.yaml
- tests/default_settings/v13.0/prod.yaml
- tests/default_settings/v13.0/test.yaml
- tests/default_settings/v7.0/prod.yaml
- tests/default_settings/v7.0/test.yaml
- tests/default_settings/v8.0/prod.yaml
- tests/default_settings/v8.0/test.yaml
- tests/default_settings/v9.0/prod.yaml
- tests/default_settings/v9.0/test.yaml
- tests/samples/alt-domains/prod.yaml
- tests/samples/cidr-whitelist/prod.yaml
- tests/samples/cidr-whitelist/test.yaml
- tests/test_default_settings.py
- tests/test_nitpicking.py
That gives errors in Traefik 2 such as this:
```
ERRO[2020-04-03T13:46:39Z] error while parsing rule Host(`www.example.com`) && (
Path(`/web`, `/web/{anything:.*}`) ||
Path(`/website/info`, `/website/info/{anything:.*}`)
)
: 3:55: expected ')', found newline (and 1 more errors)  entryPointName=web-main routerName=example-odoo-12-0-prod-forbidden-crawlers@docker
```
@Tecnativa TT23300
> Remove newlines in Traefik labels

- copier.yml
https://github.com/tomav/docker-mailserver/issues/1428 is a nasty problem that it's better to avoid if possible (and about 100% of the times it's possible).
> Warn about SMTP on port 465

- docs/scaffolding2copier.sh
- migrations.py
- tests/test_transition_to_copier.py
Without this patch, if any of these files was already removed, the migration would fail with `FileNotFoundError`.
> Fix transition when missing files

- CONTRIBUTING.md
- tasks.py
- tasks_downstream.py
- tests/default_settings/v10.0/tasks.py
- tests/default_settings/v11.0/tasks.py
- tests/default_settings/v12.0/tasks.py
- tests/default_settings/v13.0/tasks.py
- tests/default_settings/v7.0/tasks.py
- tests/default_settings/v8.0/tasks.py
- tests/default_settings/v9.0/tasks.py
- tests/test_default_settings.py
Invoke is smart enough to let users execute a `tasks.py` that is found somewhere upper in the file tree. However, that would be executed under user's CWD, which is not ideal for many tasks here.
I change to use absolute paths everywhere.
> Make tasks work from any subpath

- copier.yml
- migrations.py
- tasks.py
- tasks_downstream.py
- tests/default_settings/v10.0/tasks.py
- tests/default_settings/v11.0/tasks.py
- tests/default_settings/v12.0/tasks.py
- tests/default_settings/v13.0/tasks.py
- tests/default_settings/v7.0/tasks.py
- tests/default_settings/v8.0/tasks.py
- tests/default_settings/v9.0/tasks.py
- tests/test_default_settings.py
- tests/test_migrations.py
In doodba-copier-template, the `odoo/auto` folder is not provided just like it was with `doodba-scaffolding`.
When docker-compose needs it, docker it autogenerates it, and since docker >= root, the folder is owned by root. Then, the inner odoo process runs with lower permissions (same UID as host dev) and cannot symlink addons.
Here I fix #36 by creating `odoo/auto` with proper UID when executing `invoke develop`. There's also a new migration script that autoremoves that from the git tree if present, since that wasn't done before and a scaffolding might be coming from `doodba-scaffolding` where it was a present, git-tracked file.
However, for users that already had it created as root, the only workaround is to fix that folder's permissions or remove it manually as root. Sorry for that...
> Fix odoo/auto folder created with wrong permissions

- tasks.py
If using a invoke package as supplied by your distro, and it happens that your distro removes vendored code (this happens with `dnf install invoke` in Fedora 32), tasks would fail.
This little change avoids that failure. Possibly the mock wouldn't be necessary, but it also doesn't harm.
> Support unvendored yaml module in tasks

- .vscode/extensions.json
- tests/default_settings/v10.0/.vscode/extensions.json
- tests/default_settings/v11.0/.vscode/extensions.json
- tests/default_settings/v12.0/.vscode/extensions.json
- tests/default_settings/v13.0/.vscode/extensions.json
- tests/default_settings/v7.0/.vscode/extensions.json
- tests/default_settings/v8.0/.vscode/extensions.json
- tests/default_settings/v9.0/.vscode/extensions.json
The previous extension was buggy, causing random crashes in VSCode extensions host.
This one seems better, and is backed by Red Hat so it should have a brighter future. It provides similar benefits.
> Change recommended XML extension for VSCode

- .pre-commit-config.yaml.jinja
- tasks.py
- tests/default_settings/v10.0/.pre-commit-config.yaml
- tests/default_settings/v7.0/.pre-commit-config.yaml
- tests/default_settings/v8.0/.pre-commit-config.yaml
- tests/default_settings/v9.0/.pre-commit-config.yaml
- tests/test_nitpicking.py
This check will possibly fail with syntax errors in py2 code, and has no utility there. Remove it.
Also add test about specific pre-commit stuff, to be able to remove scaffoldign samples in the future.
> Remove debug-statements in py2-only codebases

- .pre-commit-config.yaml.jinja
- devel.yaml.jinja
- tests/default_settings/v10.0/.pre-commit-config.yaml
- tests/default_settings/v10.0/devel.yaml
- tests/default_settings/v11.0/.pre-commit-config.yaml
- tests/default_settings/v11.0/devel.yaml
- tests/default_settings/v12.0/.pre-commit-config.yaml
- tests/default_settings/v12.0/devel.yaml
- tests/default_settings/v13.0/.pre-commit-config.yaml
- tests/default_settings/v13.0/devel.yaml
- tests/default_settings/v7.0/.pre-commit-config.yaml
- tests/default_settings/v7.0/devel.yaml
- tests/default_settings/v8.0/.pre-commit-config.yaml
- tests/default_settings/v8.0/devel.yaml
- tests/default_settings/v9.0/.pre-commit-config.yaml
- tests/default_settings/v9.0/devel.yaml
- tests/test_nitpicking.py
For some reason, this was working before with no problem, although all code was mounted in readonly mode to avoid some root user inside your container writing files in your host system that your user wouldn't have permissions to later delete.
But after merging https://github.com/Tecnativa/doodba/pull/311, sometimes odoo fails when autoreloading because it tries to write `*.pyc` files where it can't.
This should fix it. BTW I update MQT code.
> Avoid writing python bytecode in devel

- .vscode/settings.json.jinja
VSCode's XML formatter conflicts with prettier, and is actually buggy. Also VSCode prettier extension doesn't include the XML prettier plugin.
So, it's better to disable it and leave pre-commit do its stuff.
> Do not format on save XML files

- devel.yaml.jinja
- docs/daily-usage.md
- docs/faq.md
Mounting only the `addons` subfolder made sense in old times when we had to fight with UIDs and all that 💩.
We can now mount the whole `auto` folder to have more room of communication from the container to the development host. This will make JS test development much easier once https://github.com/Tecnativa/doodba/pull/316 lands.
> Mount all /opt/auto in devel

- .vscode/tasks.json.jinja
Invoke is recommended to be installed with pipx, and in such environment this will not work.
Use invoke bin instead.
> Fix invoke invocation (😁)

- common.yaml.jinja
- copier.yml
- docs/scaffolding2copier.sh
- tests/test_settings_effect.py
Following https://github.com/Tecnativa/docker-duplicity/pull/35, suggest using boto3 backend by default, which is expected to work more reliably from now on. The URL shape differs, though.
> Suggest boto3+s3:// backups by default

- README.md
- tasks_downstream.py
Without having pipx installed, you will get an error after answering copier questions:
/bin/bash: pipx: command not found
I know about the code that tries to install pipx:
https://github.com/Tecnativa/doodba-copier-template/blob/1b018201c3fad9da43a615cad481a3a217d29f48/tasks_downstream.py#L83
But it doesn't work if you call copier without sudo
```
> Running task 1 of 1: invoke develop
/bin/bash: pipx: command not found
Collecting pipx
Downloading https://files.pythonhosted.org/packages/b7/63/f8a8119ff7abd5833c41ec0d7c0d46502462aab9a7bb649502723127289a/pipx-0.15.4.0-py3-none-any.whl
Collecting userpath (from pipx)
Downloading https://files.pythonhosted.org/packages/d8/1e/bad15e27cf1190f24d837205aaddfe855ef920bb6ab162e3df3506c51e94/userpath-1.4.0-py2.py3-none-any.whl
Collecting …
```
> README: add dependencies to requirements

- poetry.lock
- pyproject.toml
This is an important update, as it includes Git 2.28 support, which is being used now in Github Actions.
This should fix the branch.
> Update to copier 4.1.0

- devel.yaml.jinja
- docs/daily-usage.md
[pgweb](http://sosedoff.github.io/pgweb/) is a small, beautiful and quick way of inspecting a postgres database.
Similar to pgadmin, which was requested long ago in https://github.com/Tecnativa/doodba-scaffolding/pull/10, but never got merged because it didn't provide a very good out-of-the-box experience. pgweb, instead, can be (and is) configured through a simple environment variable, which makes that just browsing http://localhost:8081 renders a nice view of all the database structure, don't having to deal with connections, setup, passwords, etc.
> Include pgweb in the default devel toolbelt

- devel.yaml.jinja
Previous hack made it quick to stop the `wdb.server.py` process, which doesn't react properly to `SIGTERM` as explained in https://github.com/Kozea/wdb/issues/136.
However, if this process was still alive, when powering off the computer it took forever to kill it. Thus, using this alternative hack is better, because it uses docker's built-in `tini` to reap child processes. It is still fast, but it also helps the host's process reaper to work reliably.
BTW I update MQT submodule.
> Update wdb stop signal hack

- copier.yml
- poetry.lock
- pyproject.toml
Now that copier v5 will not autoupdate to prereleases by default thanks to https://github.com/copier-org/copier/pull/254, I set the domain update to be triggered since v2a0, so I'll be able to alpha-tag the template and test it properly.
@Tecnativa TT23705
> Allow testing v2 migration

- common.yaml.jinja
- migrations.py
- setup-devel.yaml.jinja
- tests/test_migrations.py
[In template v1.x it was hardcoded to be `letsencrypt`][1]. After migrating template, it must be the same.
TT23705
[1]: https://github.com/Tecnativa/doodba-copier-template/blob/ab7a378e473ab3b15a5db811f33715024c9f2b44/prod.yaml.jinja#L97
> Properly migrate Traefik 2 cert resolver

- _macros.jinja
- _traefik1_labels.yml.jinja
- common.yaml.jinja
- test.yaml.jinja
- Remove some unwanted whitespace.
- Make `first_main_domain` macro actually callable.
- Never set `hostname: "None"` to odoo service.
- Add longpolling port.
TT23705
> Polish bugs detected in v2.0.0a4

- _traefik1_labels.yml.jinja
- _traefik2_labels.yml.jinja
If there's a path prefix, no need to include longpolling and forbiddenCrawlers routers.
TT23705
> Remove absurd labels

- .pre-commit-config.yaml.jinja
If you lint before formatting, it might happen that the linter warns you about things that the formatter will fix. Absurd.
Use a saner order here, now that it's getting updated.
> Format first, lint last

- _macros.jinja
- common.yaml.jinja
- copier.yml
- prod.yaml.jinja
- test.yaml.jinja
- tests/test_nitpicking.py
Odoo itself supports multiple domains, but has a notion of what the main domain is (a.k.a. `web.base.url`).
From now on, the notion of what the main domain is gets coded, documented and tested. The final result gets exposed as the `doodba.domain.main` label in the `odoo` service, just in case you need to extract it for any purposes.
@Tecnativa TT23705
> Specify and test the main domain

- docs/scaffolding2copier.sh
From v2.0.0 onwards, this version should never ever change again.
> Bump default template update version

- .vscode/launch.json.jinja
- devel.yaml.jinja
- docs/daily-usage.md
This should let the developer at least boot 2 instances with different versions.
Not perfect yet, but better than before indeed.
Docs updated.
> Open all ports in devel prefixed by version

- .pre-commit-config.yaml.jinja
- tests/conftest.py
- tests/test_nitpicking.py
After using v2.0.0, sadly we missed another alpha and got hit by https://github.com/OCA/pylint-odoo/issues/296.
This fixes the situation by pinning the isort version. Also it tests the actual execution of pylint-odoo in pre-commit context, instead of just asserting its configuration.
TT23969
> Fix incompatibility between pylint-odoo and isort

- .pre-commit-config.yaml.jinja
- tests/test_nitpicking.py
This fix is needed to avoid https://github.com/PyCQA/isort/issues/1481.
> Fix isort 5 compatibility with black

- _traefik1_labels.yml.jinja
It shouldn't include `.frontend`.
TT25531
> Fix Traefik v1 port label

- tests/test_nitpicking.py
[This test fails under some circumstances if the commit where it is tested contains a tag][1].
Add a dumb commit to make it resilient.
[1]: https://github.com/Tecnativa/doodba-copier-template/runs/1122075347
> Fix non-resilient test

- .pre-commit-config.yaml.jinja
With the combination that landed with latest update, XML code couldn't make use of `` and `` tags.
Besides, since https://github.com/prettier/prettier/pull/8829 was merged, we don't need to have 2 separate prettier steps anymore; XML files get formatted in the 1st one automatically.
With this patch, the now-duplicated step is removed and the XML plugin is updated, so we get saner ignores. Also, XML files will look even prettier now.
> Update prettier XML plugin and fix incompatibility

- _traefik1_labels.yml.jinja
- tests/conftest.py
- tests/test_routing.py
It must be `entryPoints` and not `entrypoints`.
TT25671
> Fix typo in traefik 1 entrypoints

- copier.yml
- migrations.py
- tasks.py.jinja
- tests/test_migrations.py
Fix subproject generated tasks.py file, which always hits some pre-commit change. Now it's included upstream to avoid that pre-commit diff.
Also a migration script handles removal of `.vscode/{launch,tasks}.json` files.
> Polish 2.1.0 release

- .prettierrc.yml
- .prettierrc.yml.jinja
Newer prettier XML plugin is giving some headaches because it disrespects whitespace inside attributes also. This can transform things like `href` to some wrong value.
We choose to default to strict. According to [prettier-xml docs][1], `xmlWhitespaceSensitivity` defaults to `strict`, so technically we don't really need to establish that setting.
Then the desired subproject configuration matches the same as the templates, so the `.jinja` file can be just removed.
@Tecnativa TT25707
> Set xmlWhitespaceSensitivity=strict for prettier

- tasks.py.jinja
- tests/test_nitpicking.py
- Git repos workspace folders ordered from A-Z
- Odoo, Private and Root folder last
TT25731
> [FIX] Order VSCode folders A-Z

- copier.yml
It allows to quickly apply default values on all other options by pressing Enter button.
Such approach is especially useful for local modules development
----------------
I'd actually like to move just odoo_version attribute, but the attributes are grouped, so I moved whole ``odoo_`` group and reordered making first the attributes most important for modules development.
As for now, I need to slowly click enter to don't miss odoo_version question -- the only question where I don't use default value
------------------
I just noticed that it's stable branch. Am I supposed to send it to devel branch instead?
> Ask odoo version first

- devel.yaml.jinja
- tasks.py.jinja
Seems like debugpy is the recommended library for debugging Python with VSCode, so it makes sense to make this transition.
https://code.visualstudio.com/docs/python/debugging#_debugging-by-attaching-over-a-network-connection 
https://github.com/microsoft/debugpy
This updates the template, but projects Doodba needs to be updated (see https://github.com/Tecnativa/doodba/pull/324)
Tecnativa-Task #25875
> Update ptvsd -> debugpy

- common.yaml.jinja
This edition is the same image, but published directly on Github, which works nicer with users in countries that USA doesn't like.
@Tecnativa TT22772
> Use ghcr.io version of tecnativa/postgres-autoconf image

- common.yaml.jinja
While debugging https://github.com/OCA/stock-logistics-workflow/pull/712, [this explain-analyzed query][1] shows that a database with 1.25M quants takes ~210 MB of memory to perform a quicksort memory sort operation, while running [`_merge_quants()`][2].
I'll default to giving about the double of that, to avoid further bottlenecks.
@Tecnativa TT26171
[1]: https://explain.depesz.com/s/3Ivw
[2]: https://github.com/odoo/odoo/blob/1527db8cd719c487ace02fca9fde21430e31d350/addons/stock/models/stock_quant.py#L317-L335
> Increase default postgres work_mem

- common.yaml.jinja
It turns out the deletion process was deleting nothing because full backups were never being triggered, due to that only being automatic upstream in `*-s3` flavoured tags.
> Update subrepo and add full weekly backups when deletion is enabled 

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
See https://github.com/prettier/prettier/issues/9459
> Migrate prettier from prettier/prettier to prettier/pre-commit

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
This seems to be a better fix (for now) than #149 because it just fixes the npm 7 installation problem without having to worry about https://github.com/prettier/pre-commit/pull/17 or https://github.com/prettier/pre-commit/pull/18 for the moment.
Once those are solved, we can start using the new repo.
> Pin nodejs versions for pre-commit

- _traefik1_labels.yml.jinja
Without this label, Traefik 1 keeps trying to download invalid certs, even when there are more specific routers that would invalidate this rule.
> Add traefik 1 main domain

- .vscode/extensions.json
- tasks.py.jinja
Add [Tasks extension](https://marketplace.visualstudio.com/items?itemName=actboy168.tasks) to allow launching Start and Stop Odoo tasks from the bottom tasks bar. 
I've added it with some icons and color, but we can also leave them blank and add some text to describe.
> Add buttons to run start and stop tasks

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
We are starting to get https://github.com/pre-commit/pre-commit/issues/1674 and similar errors. Seems like we need to migrate to `prettier/pre-commit` after all... This applies a similar fix to https://github.com/OCA/oca-addons-repo-template/pull/38. See there for details.
* Revert "Pin nodejs versions for pre-commit"
This reverts commit 955f6ddfcf98fbfadc9aa257cb8652813eb6337c.
* Re-apply "Migrate prettier from prettier/prettier to prettier/pre-commit"
This reverts commit 1f851935d09963d9ae4138be0ba5d038c4735382.
* Improve prettier pre-commit configuration
After https://github.com/prettier/pre-commit/pull/17 was fixed
* Update to v2.1.2 in template config
> Migrate from prettier/prettier to prettier/pre-commit

- tasks.py.jinja
- tests/pytest.ini
- tests/test_tasks_downstream.py
1. Add invoke task to easily run Odoo tests. It accepts both the name of the module(s) to test, or it can detect the module you are currently working on if you pass a working directory or file. It also allows to run the tests in debug mode.
2. Add VSCode tasks that match invoke task and respective options. A normal task automatically passes to invoke the file you are working on.
3. Add VSCode debug configurations for debugging Odoo tests.
4. Add invoke task to easily install Odoo modules. You can pass the name(s), or also `--core`, `--extra` or `--private` options to install everyting.
It would also be good to incorporate https://github.com/Tecnativa/doodba-copier-template/pull/139 here, once it is finished.
TT26483
> IMP: Add Odoo tests and install task

- docs/faq.md
Recently prettier got broken badly (see https://github.com/prettier/prettier/issues/9459 and all the related PRs/issues there).
This explains how to avoid that problem when updating templates.
To know if this is the problem you're facing, this is the log that you'd find if you cannot install prettier due to this problem:
<details>
```
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1
Command line: | /usr/bin/git commit --allow-empty -am 'dumb commit 2'
Stderr:       | [INFO] Installing environment for https://github.com/prettier/prettier.
| [INFO] Once installed this environment will be reused.
| [INFO] This may take a few minutes...
| An unexpected error has occurred: CalledProcessError: command: ('/var/home/yajo/.cache/pre-commit/repow9n8yvh_/node_env-default/bin/ …
```
> Explain how to avoid the prettiermageddon when updating

- .vscode/settings.json.jinja
- tasks_downstream.py
It turns out this setting is ignored if set as folder setting.
> Move search.followSymlinks to workspace setting

- devel.yaml.jinja
[It is needed when developing for `website_slides`][1].
I also refactored a bit how these proxies are generated. This renames them, but it shouldn't be a big problem because it is just in the devel environment. Now it'll be easier to extend.
[1]: https://github.com/odoo/odoo/blob/62a18bdb372e234107fd2099a2df5f9e3a442c96/addons/website_slides/models/slide_slide.py#L847
> Proxy www.googleapis.com

- .github/workflows/test.yml
`set-env` command has been deprecated and disabled: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Suggested alternative is to echo vars to default file: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
> Update tests to set env variables through file instead of set-env

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
- tasks_downstream.py
1. Migrate from prettier/pre-commit to pre-commit/mirrors-prettier (#prettiermageddon 2.0)
2. Simplify VSCode debugger configurations: Remove some tasks, now only having
- Start Odoo (in debug mode) and debug python
- Attach to Python debugger
- Attach to JS debugger using Chromium or Firefox (1 task each)
- Test and debug current module
> Small fixes and improvements

- tasks_downstream.py
After auto-reload as been removed, it is more difficult to debug when making regular changes. Start task does not recreate Odoo container, so no changes are reflected.
This ensures Odoo is recreated after every start command.
It also adds a VSCode task and button to easily restart Odoo and the proxy.
It would be nice to do it automatically when you press the "Restart" button in the VSCode debugger, but AFAICS that only restarts the "Attach" configurations, which will always find the debugger already running, leaving no option but to "Disconnect" and launch again. 
If you press "Restart Odoo", the debugging session is also disconnected and needs to be lauched again.
> Add restart options to reload environment

- tasks_downstream.py
- tests/test_nitpicking.py
According to [the docs][1], `${workspaceRoot}` is now deprecated:
[1]: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_debugging
> workspaceRoot -> workspaceFolder

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
`pip` > 20.3 starts implementing a new dependency resolver which disallows having conflicting dependencies in the same environment. https://pip.pypa.io/en/stable/user_guide/?highlight=resolver#changes-to-the-pip-dependency-resolver-in-20-3-2020
This breaks the current pre-commit installation.
The errors are:
- `pylint-odoo` requires a specific version of `isort` and `pylint`, so when need to pin those
- The version of oca `maintainer-tools` we were using has a conflicting dependency with `docutils`
This fix pins the required versions until the hooks upstream update their dependencies to be compatible with each other.
TT27232
> Fix pre commit deps

- .pre-commit-config.yaml.jinja
- docs/faq.md
Fix from https://github.com/Tecnativa/doodba-copier-template/pull/197 was incomplete.
This fixes it.
TT27232
> Fix pre-commit pylint versioning to work with pip 20.3

- {{ _copier_conf.answers_file }}.jinja
This confuses users. Following https://github.com/copier-org/copier/pull/317 I add this warn.
> Warn about manual edits

- .pre-commit-config.yaml.jinja
`isort` version was pinned to avoid `pip` installation conflicts (See https://github.com/Tecnativa/doodba-copier-template/pull/197/commits/5dcdeb70dfa23378581d9975a64dc834504afec4 and https://github.com/OCA/pylint-odoo/issues/306)
Seems like this issue has been fixed upstream (See https://github.com/OCA/pylint-odoo/commit/fd90fc89d4c03db01a0290f1fc84b5cc2f1e78c9)
Therefore, we can bump the `pylint-odoo` version to include the fix and loose the old `isort` version.
Partially reverts 5dcdeb70dfa23378581d9975a64dc834504afec4
@Tecnativa
TT27232
> Update pylint configuration

- tasks_downstream.py
Seems to be necessary after `docker` update to v20.10+
Fixes #223
@Tecnativa
TT28516
ping @Yajo
> Run git-aggreator in a tty enabled env

- README.md.jinja
- common.yaml.jinja
- copier.yml
- devel.yaml.jinja
- docs/daily-usage.md
- tasks_downstream.py
- tests/conftest.py
- tests/test_settings_effect.py
- tests/test_tasks_downstream.py
Images migrated to GHCR so far:
- docker-duplicity 
- docker-mailserver (the image we were using had been deprecated and might have been outdated. I referenced the stable release, but we should still do some testing before releasing it officially)
- docker-whitelist (depends on https://github.com/Tecnativa/docker-whitelist/pull/6)
Still waiting on response from other maintainers to have other images migrated as well, but this should reduce the impact of the restrictions of DockerHub already.
Also, some small improvements (suggestions):
1. Add a button to see container logs:
As happens with the `Test module` button, it launches the task and automatically focuses the terminal there to see the logs.
2. The `invoke start` command was recreating the containers even if they had just been …
> Migrate images to ghcr + Small improvements

- tasks_downstream.py
In 49cf5dbb1fe52462d84524221360b89972ffa731 we added this hardcoding because Pylance just didn't work fine.
According to my recent tests, latest versions work just fine. It's actually much faster to load file symbols.
By removing this setting from the workspace, we let each user choose the preferred language server.
> Don't hardcode Jedi anymore

- .github/workflows/test.yml
- tasks.py
- tasks_downstream.py
- tests/conftest.py
- tests/test_nitpicking.py
- tests/test_tasks_downstream.py
Some improvements to the `resetdb`, `install` and `test` flows:
1. Allow to prepare DB with config (Only for v11+)
1.1. In resetdb with flag
1.2. In a separate `preparedb` task
2. Improve `test` task
2.1. Test all core, extra and private modules with one command.
2.2. Test only explicit list of modules and skip some if needed (for multi-stage testing) (Only for v12+)
3. Improve `resetdb` task:
3.1 Install all core, extra and private modules present with extra flags
3.2 Install only dependencies of any list of modules passed.
4. Improve tests
4.1. Run docker tests by default
4.2. Add tests for new additions
5. Install `click-odoo` from acsone/click-odoo-contrib#93 to fix bug
TT27635
> Improve install and test tasks

- tasks_downstream.py
Multidb environments are harder to test because any http test lands in the db selector instead of the actual instance.
The solution is to add a dbfilter, but that would become problematic in devel when doing db backups or resetdb.
Thus, when `invoke test`ing, add automatically the DB_FILTER, so there's one less thing to worry about.
> feat: when testing, add DB_FILTER=devel

- devel.yaml.jinja
- tasks_downstream.py
- tests/conftest.py
- tests/test_tasks_downstream.py
As mentioned in #244 (comment)
multiple DBs in an instance will cause problems in http tests
that land in the DB selector
When testing locally, the same can happend when developing controllers and APIs
When there is no session cookie, many calls fail as there is no explicit DB associated
We can limit that DB as, in devel, "devel" will be used pretty much 99% of the time
For the other cases, we can edit the DB filter manuallly
We can also remove it from the test task, as it will be included
in the docker compose file directly
---
Do a `docker-compose down` instead of a `stop`
1. When developing, this is a task generally performed when wanting to leave for another environment, not really when wanting to restart the environment relatively fast. For that, we have `restart`.
2. If regular down …
> Move db filter to docker compose + Docker-compose down instead of stop

- tasks_downstream.py
Append "/" to the module name before to comply with Odoo's filter mechanism
> Filter module tests correctly

- .github/ISSUE_TEMPLATE/feature_request.md
This avoids the need to remove by hand all that 🗑️.
> fix: publisher info in comments

- .vscode/doodba.code-snippets
Add a simple snippet to make it easier to add a proxy with `docker-whitelist`:
https://user-images.githubusercontent.com/38977934/121135578-8dea7080-c82c-11eb-8749-8aa1a690337d.mp4
> Add Docker Whitelist Proxy code snippet

- tasks_downstream.py
The file name that is passed to the function might be a symlink. 
Example: In Fedora SilverBlue, `/home/` is a symlink to `/var/home`. If you have a home folder (along with VSCode settings) that comes from a backed up system where home is `/home`, VSCode will pass the file name with `/home` as root, not `/var/home`, causing this script to fail. This avoids that.
> Resolve symlinks before attempting to find module name from file

- tasks_downstream.py
Give the option to include in the base function, but we won't want them by default, both when testing modules and when resetting the DB.
> Don't include non-installable addons when retrieving list

- odoo/custom/build.d/{% if odoo_version < 11 %}10-fix-certs{% endif %}.jinja
- tasks_downstream.py
After the root LE certificate expired in October 1st, the list needs to be updated.
The alternative root certificate (ISRG Root X1) is already present as it was packaged with the old `ca-certificates`, so we just need to remove the old conflicting one to force the new one to be used.
See more at https://letsencrypt.org/certificates/
Closes https://github.com/Tecnativa/doodba-copier-template/issues/278
@Tecnativa
TT32281
> Fix root certificate issue for old Doodba images

- common.yaml.jinja
- copier.yml
- migrations.py
- prod.yaml.jinja
- tests/test_migrations.py
- tests/test_settings_effect.py
It doesn't make sense to add a DB filter to devel and test environments.
It makes sense to provide a saner default (only for production) where the filter matches any database prefixed with the name of the default database.
Benefits from https://github.com/Tecnativa/docker-duplicity/pull/75 to allow backing up only the used DBs by default.
@Tecnativa TT32631
> feat: add dbfilter only to prod, defaulting to database name prefix

- common.yaml.jinja
- devel.yaml.jinja
- docs/faq.md
This patch downloads the exact same images, but removes ambiguity.
When using podman as backend, you get this error with `docker-compose pull`:
ERROR: for pgweb  failed to resolve image name: short-name resolution enforced but cannot prompt without a TTY
This is because podman supports configurable default registries to resolve ambiguous names, and when pulling an ambiguous-named image, it asks interactively how to resolve it:
```sh
podman pull sosedoff/pgweb
? Please select an image:
▸ registry.fedoraproject.org/sosedoff/pgweb:latest
registry.access.redhat.com/sosedoff/pgweb:latest
docker.io/sosedoff/pgweb:latest
quay.io/sosedoff/pgweb:latest
```
Interactive prompts are disabled when using podman through the socket, which is the case when using docker-compose, and so it just fails.
With …
> feat: full qualified image name everywhere

- .github/workflows/test.yml
- tasks_downstream.py
Invoke's vendored pyyaml is incompatible with Python 3.10, as seen in https://github.com/pyinvoke/invoke/issues/820.
As we're using it, a good workaround is to use system's un-vendored version if available.
When installing invoke with pipx, you can get the normal pyyaml with:
```sh
pipx install invoke
pipx inject invoke pyyaml
```
That + this patch fixes the problem.
Besides, I'm removing builds for py3.6, which is EOL.
> fix(tasks): invoke's yaml incompatible with python 3.10

- _traefik1_labels.yml.jinja
They have the same name for v1 and v2, so having them in both places caused a conflict
> Delete permanent redirect rule from Traefik 1 labels config

- _traefik2_labels.yml.jinja
https://doc.traefik.io/traefik/middlewares/http/redirectregex/#permanent explains how to configure this for Traefik 2. It was being configured as for Traefik 1.
@moduon
> fix: generate permanent redirections properly

- tasks_downstream.py
Without this patch, if you mispell one git remote URI, `invoke git-aggregate` will get stuck, and the only clue you'll get to know why will be a message like this buried under a lot of "success" logs:
Username for 'https://github.com':
Now, you get a proper error because there's no TTy associated with the process, so it cannot ask for input and will produce a meaningful error.
@moduon MT-460
> fix: remove tty from git-aggregate task

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
Currently gitlab.com (and therefore https://gitlab.com/pycqa/flake8) is banned to some countries (such as Cuba, due to the US blockade).
So, I think we can change the pre-commit configuration to use the GITHUB flake8 repository instead of the GITLAB one (https://gitlab.com/pycqa/flake8 -> https://github.com/pycqa/ flake8) since that gitlab repository is a mirror of the github one. This way we will have the original repository and also we do not affect anyone from any country in the use of pre-commit with this configuration.
> [IMP] Change pre-commit flake8 URL

- _traefik2_labels.yml.jinja
- test.yaml.jinja
Today I started noticing warnings like this in Traefik logs:
SSLRedirect is deprecated, please use entrypoint redirection instead.
Indeed [the redirection method we were using is deprecated][1]. I changed it for [the most similar one][2].
[1]: https://doc.traefik.io/traefik/migration/v2/#headers-middleware-ssl-redirect-options
[2]: https://doc.traefik.io/traefik/middlewares/http/redirectscheme/
> fix: update https redirection method

- tasks_downstream.py
This will make it work with podman 4 out of the box. Podman 4 still doesn't support `--link`, which is used by docker-compose when starting a parallel container. The fix is quite simple: just stop odoo before installing. The vscode task automatically calls `restart` after installation, which makes Odoo start again. Docker users will notice no difference.
> fix(podman): stop odoo before installing module

- .vscode/settings.json
- tasks_downstream.py
- `python.pythonPath` is now `python.defaultInterpreterPath` (https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter)
cc @Tecnativa
> [FIX] Update vscode python obsolete parameters

- .eslintrc.yml.jinja
- tests/samples/mqt-diffs/v10.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v10.0-.pylintrc.diff
- tests/samples/mqt-diffs/v11.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v11.0-.pylintrc.diff
- tests/samples/mqt-diffs/v12.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v12.0-.pylintrc.diff
- tests/samples/mqt-diffs/v13.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v13.0-.pylintrc.diff
- tests/samples/mqt-diffs/v14.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v14.0-.pylintrc.diff
- tests/samples/mqt-diffs/v15.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v15.0-.pylintrc.diff
- tests/samples/mqt-diffs/v16.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v16.0-.pylintrc.diff
- tests/samples/mqt-diffs/v8.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v8.0-.pylintrc.diff
- tests/samples/mqt-diffs/v9.0-.pylintrc-mandatory.diff
- tests/samples/mqt-diffs/v9.0-.pylintrc.diff
- Get eslint fix for sourceType.
- Get latest definitions.
- Change eslint source path.
To check the differences in the submodule, go to
https://github.com/OCA/oca-addons-repo-template/compare/09544010ba14f9ca1a0e05b86bd8e31dc72494d3..master
> [UPD] Update oca-addons-repo-template to latest branch

- .vscode/extensions.json
- tasks_downstream.py
Microsoft is moving Black support to its own extension: https://github.com/microsoft/vscode-black-formatter
There's no need to hardcode this formatter here. Besides, if you're using the Black-dedicated one, this way you get to use it also in DCT projects.
> fix(tasks): remove python hardcoded formatter

- copier.yml
The nomenclature used is not correct and not admitted by all versions of the library.
> [FIX] Remove invalid initial version

- .pre-commit-config.yaml
- .pre-commit-config.yaml.jinja
Fixes:
```
|           RuntimeError: The Poetry configuration is invalid:
|             - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```
see https://github.com/PyCQA/isort/issues/2077
> [FIX] pre-commit isort version

- common.yaml.jinja
`domainname` is not supported when the docker backend is podman. It is required to compute appropriately the prefixes in s3 flavored images.
With this patch, we make the container compatible with both docker and podman.
@moduon MT-2568
> fix(podman): allow downloading correct backups

- .vscode/extensions.json
Odoo uses scss. This extension only adds support for sass. Thus, it's useless to recommend it.
> fix: don't recommend sass-indented extension

- _traefik1_labels.yml.jinja
- _traefik2_labels.yml.jinja
- devel.yaml.jinja
- prod.yaml.jinja
- test.yaml.jinja
As mentioned in https://github.com/Tecnativa/doodba/discussions/530, the old `/longpolling/` route was replaced by `/websocket` in Odoo 16.0 (see https://github.com/odoo/odoo/pull/75510). Currently, this results in the following error when a client tries to access the latter route (with the exception of threaded-mode odoo):
```
Traceback (most recent call last):
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 2002, in __call__
response = request._serve_db()
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1588, in _serve_db
return service_model.retrying(self._serve_ir_http, self.env)
File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
result = func()
File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1615, in _serve_ir_http
response = …
```
> [FIX] Update longpolling route for Odoo 16.0

- prod.yaml.jinja
This makes all look more consistent when rendered.
> style: whitespace before smtp service

- .module-readme.rst.j2
- .pre-commit-config.yaml.jinja
This is the configuration recommended upstream: https://copier.readthedocs.io/en/stable/updating/#preventing-commit-of-merge-conflicts
It is more important now that Copier supports inline conflict markers on updates.
@moduon MT-2626
> fix: safer merge conflict commit protection

- .pre-commit-config.yaml.jinja
As mentioned here: https://github.com/Tecnativa/doodba-copier-template/pull/401#issuecomment-1778858811 'odoo-pre-commit-hooks' hooks are added.
Related info: https://github.com/OCA/odoo-pre-commit-hooks/tree/main?tab=readme-ov-file#usage-pre-commit-configyaml
> imp: pre-commit config: add 'odoo_pre_commit_hooks'

- common.yaml.jinja
If not, mails are not delivered.
@Tecnativa
> [FIX] The SMTP domain should prefix `smtp`

- tasks_downstream.py
If not, pre-commit in the target repository will complain about it.
> [FIX] Avoid overpassing line length in tasks_downstream

- .flake8
- .pre-commit-config.yaml.jinja
referencig to this PR https://github.com/Tecnativa/doodba-copier-template/pull/422 , while adding ignore in .flake8 does not apply it, the solutions is to add the ignore on pre-commit.yaml.jinja
> [FIX] Undoo PR 422 changes and set correct solution

- .ruff.toml.jinja
@moduon MT-4544
These versions match the ones in the dockerfiles of doodba. Well, some of them are older than 3.7, but ruff doesn't support that, so by putting py37 on those, we get closer to something useful.
> fix(ruff): consider odoo version to establish python target version

- .github/workflows/test.yml
- docs/faq.md
These instructions are quite outdated. Podman works flawlessly for development after its v4.
> docs: stabilize podman support for devel

- .pre-commit-config.yaml.jinja
As you can see reported in https://github.com/prettier/prettier/issues/15696, prettier 3.x won't work with plugins under the context of pre-commit. In practice, this means for us that XML won't get auto-formatted.
Pinning latest working combination.
@moduon MT-5455
> fix(prettier): rollback to working version

- tasks_downstream.py
cc @Tecnativa
To avoid error when you start an instance and try to start twice 
```
container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'
```
ping @josep-tecnativa @carlosdauden
> [IMP] Try use docker compose command v2 by default

- tasks_downstream.py
In this change https://github.com/Tecnativa/doodba-copier-template/commit/e2bc946fa20edc34e9007c40c3d41e0491710fca is always used docker compose. In docker versions 24.0.6 or lower, this is incompatible, and needs to use docker-compose
>  [FIX] Correct always using docker compose, even if it not compatible.

- .github/workflows/test.yml
- README.md
- Small changes in the readme
- Restricted the tests to the "main" branch... now the indicator should be displayed:
> Improve repository

- .pre-commit-config.yaml.jinja
Use new features from maintainer-tools to skip rewriting readmes if fragments did not change and to convert them to markdown automatically.
@moduon
> feat(pre-commit): improve addon readme generation

- .github/workflows/test.yml
- _traefik3_labels.yml.jinja
- _traefik3_paths_labels.yml.jinja
- copier.yml
- docs/scaffolding2copier.sh
- prod.yaml.jinja
- test.yaml.jinja
- tests/conftest.py
- tests/test_routing.py
New Feature Added: Doodba Copier Template Now Compatible with Traefik 3
With these changes, the Doodba Copier Template is now compatible with Traefik 3. When selecting Traefik as the proxy, you can choose which version to use. By default, version 2 is selected as it is the most stable.
Additionally, this PR includes the Traefik version in the test matrix and excludes tests with insecure connections for Traefik 3 due to incompatibilities.
> [IMP] Traeffik 3 compatibility

- _traefik3_labels.yml.jinja
Removed the conditional that prevented the Traefik 3 feature without forbidden crawlers, which was added by mistake.
> [FIX] Without forbidden crawlers

- .flake8.jinja
- .pre-commit-config.yaml.jinja
- isort.cfg.jinja
CC  @Tecnativa TT50985
As ruff is not compatible with Python versions below 3.7, the pre-commit is causing problems in Odoo versions below 13.0.
> [FIX] Pre-commit problems for odoo versions with python < 3.7

- common.yaml.jinja
- prod.yaml.jinja
- tests/test_settings_effect.py
The backup image [accepts a regexp on `DBS_TO_INCLUDE`][1]. But [Odoo uses a regexp with custom extensions][2] (`%h` and `%d`).
If you use any of those extensions, the backup jobrunner will fail with `CalledProcessError`.
Additionally, regexps usually contain a `$` symbol, which [needs to be escaped for docker-compose][3].
[1]: https://github.com/Tecnativa/docker-duplicity#dbs_to_includeexclude
[2]: https://www.odoo.com/documentation/16.0/developer/reference/cli.html#cmdoption-odoo-bin-db-filter
[3]: https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution
BREAKING CHANGE: if your dbfilter contained `$$` previously, to do that escaping yourself, you will have to convert it to a single `$`
@moduon MT-4191
> fix(backup): convert odoo regex extensions

- _traefik3_paths_labels.yml.jinja
- copier.yml
- prod.yaml.jinja
- tests/conftest.py
Since Traefik 3 is avaliable on Doodba Copier Template, we can configure with our template, a postgres exposed database. This is only working on Traefik 3.
> [ADD] Feature to expose database

- _traefik3_paths_labels.yml.jinja
Updated the template to include all domains in the external database access rule, allowing users to access the database from any configured domain.
> [DCK] Add all domains to external database connection

- test.yaml.jinja
When you use queue_job, it is common to add some configuration to it.
The canonical way to do that with doodba would be to put a file in some path such as `odoo/custom/conf.d/queue_job.conf` and contents like these:
```ini
[options]
(...)
workers = 6
server_wide_modules = base,web,queue_job
(...)
[queue_job]
channels = root:3
```
However, in that case, the file would be used too by a test environment.
Test environments have 2 workers hardcoded, to save computational power for the production instance: https://github.com/Tecnativa/doodba-copier-template/blob/e2f4efdab336d5cd32c327a007983011e1e4edbb/test.yaml.jinja#L50
However, if you configure 2 workers with `channels = root:3`, you're doomed. Any delayed action in a test environment will block the server. At least, if the amount of delayed …
> fix(queue_job): out-of-the-box support in test environments

- tasks_downstream.py
Hello, I open this PR according to the comments in this issue: (https://github.com/Tecnativa/doodba/issues/638#issuecomment-2511648434)
> [IMP] code-workspace definition: python.analysis.extraPaths

- docs/faq.md
Adding Traefik v2 and Traefik v3 configuration example.
In Traefik v3 is added postgres-entrypoint to be able to use feature developed on https://github.com/Tecnativa/doodba-copier-template/pull/479
> [IMP] Add Traefik v2 and Traefik v3 documentation

- common.yaml.jinja
- devel.yaml.jinja
- prod.yaml.jinja
- tasks_downstream.py
- test.yaml.jinja
- tests/test_postgres.py
CC @Tecnativa TT54598
When multiple Odoo projects are deployed within the same Docker network, there is a risk that an instance of Odoo may inadvertently connect to the database of another project due to identical service names. This PR addresses the issue by ensuring unique service names, preventing unintended cross-project database connections and ensuring proper project isolation.
> Using unique service db names

- tasks_downstream.py
This PR updates the workspace generation to detect doodba subprojects and add their modules from odoo/custom/src/private to the VSCode debug path. If a .copier-answers.yml indicates a doodba-copier subproject, we scan for modules there and configure them automatically for debugging. Otherwise, the script follows the existing one-level scan.
> [IMP] Support debugging modules from nested doodba subprojects in VSCode

- test.yaml.jinja
As we did on this PR https://github.com/Tecnativa/doodba-copier-template/pull/522 , we add this configuration to test.yml to avoid this error on test environment.
> [IMP] Add network alias to test.yml file

- _traefik2_labels.yml.jinja
- _traefik3_paths_labels.yml.jinja
This PR adds a middleware that rewrites X-Forwarded-Proto to https for Odoo 16+ WebSocket connections. It prevents the scheme mismatch (https vs. wss) that would otherwise trigger a public session under ODOO_BUS_PUBLIC_SAMESITE_WS=1.
cc @Tecnativa TT55574
> [FIX] WebSocket scheme mismatch for Odoo 16+ by rewriting X-Forwarded-Proto

- .vscode/extensions.json
1. [msjsdiag.debugger-for-chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) is deprecated
2. [ms-azuretools.vscode-containers](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker) is replaced by[ container tools](https://techcommunity.microsoft.com/blog/AppsonAzureBlog/major-updates-to-vs-code-docker-introducing-container-tools/4400609) 
@Tecnativa @josep-tecnativa
> [FIX] don't recomment obsolete extensions

- tasks_downstream.py
- `_logger.warn` is deprecated; use `_logger.warning` instead.
- The format string was incorrect, which caused a `TypeError: not enough arguments for format string.`
- When the module is not in the list of modules, trying to remove it results in a `ValueError: list.remove(x): x not in list`
You can reproduce the error by running the following command:
`invoke test --modules module1,module2,module3 --skip module2,module4`
@pedrobaeza @josep-tecnativa could you please review this?
> [FIX] Update skip parameter description and improve logging for missing modules

- devel.yaml.jinja
- tasks_downstream.py
`resetdb` now forwards the `INITIAL_LANG` environment variable to `click-odoo-initdb`, ensuring new databases load the specified language, and devel.yaml.jinja exposes `INITIAL_LANG` so developers can set their preferred locale directly in the compose file.
Fixes [this issue](https://github.com/Tecnativa/doodba/issues/668) 
CC @Tecnativa TT57094
> [IMP] Use INITIAL_LANG on resetdb to choose lang on devel

- common.yaml.jinja
- copier.yml
- prod.yaml.jinja
- test.yaml.jinja
This can be helpful if you want to have a single production environment
while having multiple databases for testing in staging.
@moduon MT-10847
> feat(odoo_listdb_staging): explicit option for exposing DB list in staging only

- _traefik1_paths_labels.yml.jinja
- _traefik2_labels.yml.jinja
- _traefik3_paths_labels.yml.jinja
- copier.yml
- prod.yaml.jinja
- test.yaml.jinja
This might allow to index images like favicon.
We are still testing if this fixes this issue:
As you can see, the favicon is not processed properly. The same happens in Bing.
The only reason we found is that favicon is related to web/image/website/1/favicon and traefik adds the x-robot-tag noindex.
Right now it is promising as Google Search Console App detected the favicon (before it had the same image that we find in google search). However, as we have not managed to reindex the main page, we are not 100% sure that it fixes it.
:crossed_fingers:
> [IMP] Add allowed paths
