.github/workflows/automerge.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.gitignore
tasks_downstream.py
tests/default_settings/v10.0/.gitignore
tests/default_settings/v10.0/tasks.py
tests/default_settings/v11.0/.gitignore
tests/default_settings/v11.0/tasks.py
tests/default_settings/v12.0/.gitignore
tests/default_settings/v12.0/tasks.py
tests/default_settings/v13.0/.gitignore
tests/default_settings/v13.0/tasks.py
tests/default_settings/v7.0/.gitignore
tests/default_settings/v7.0/tasks.py
tests/default_settings/v8.0/.gitignore
tests/default_settings/v8.0/tasks.py
tests/default_settings/v9.0/.gitignore
tests/default_settings/v9.0/tasks.py

This is a common installation method that provides more isolation for console apps.
It would break current workflow, so I test it to make sure support is included.

Support installing invoke and poetry with pipx

---

prod.yaml.jinja
tests/default_settings/v10.0/prod.yaml
tests/default_settings/v11.0/prod.yaml
tests/default_settings/v12.0/prod.yaml
tests/default_settings/v13.0/prod.yaml
tests/default_settings/v7.0/prod.yaml
tests/default_settings/v8.0/prod.yaml
tests/default_settings/v9.0/prod.yaml
tests/helpers.py
tests/test_settings_effect.py

It should include all provided alt domains.

Fix production alt domains

---

README.md
poetry.lock
pyproject.toml
tests/test_transition_to_copier.py

- Remove copier pre-release instructions.
- Update dependencies.
- Fix tests now that https://github.com/Tecnativa/doodba-scaffolding/pull/69 is merged.

Update for 1st release

---

copier.yml
docs/scaffolding2copier.sh
poetry.lock
pyproject.toml
tests/test_nitpicking.py
{% if project_license %}LICENSE{% endif %}.jinja

Several fixes

---

setup-devel.yaml.jinja
tasks_downstream.py
tests/default_settings/v10.0/setup-devel.yaml
tests/default_settings/v10.0/tasks.py
tests/default_settings/v11.0/setup-devel.yaml
tests/default_settings/v11.0/tasks.py
tests/default_settings/v12.0/setup-devel.yaml
tests/default_settings/v12.0/tasks.py
tests/default_settings/v13.0/setup-devel.yaml
tests/default_settings/v13.0/tasks.py
tests/default_settings/v7.0/setup-devel.yaml
tests/default_settings/v7.0/tasks.py
tests/default_settings/v8.0/setup-devel.yaml
tests/default_settings/v8.0/tasks.py
tests/default_settings/v9.0/setup-devel.yaml
tests/default_settings/v9.0/tasks.py
tests/test_default_settings.py
tests/test_doodba_qa.py

- Cannot pass ints to env.
- Cannot use `$ODOO_IMAGE` if there's no `odoo_oci_image`.

Fix git-aggregate downstream task

---

.gitignore
tests/default_settings/v10.0/.gitignore
tests/default_settings/v11.0/.gitignore
tests/default_settings/v12.0/.gitignore
tests/default_settings/v13.0/.gitignore
tests/default_settings/v7.0/.gitignore
tests/default_settings/v8.0/.gitignore
tests/default_settings/v9.0/.gitignore
tests/test_nitpicking.py

This happens mostly due to https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/177

Fix .vscode sometimes being tracked inside private

---

README.md.jinja
prod.yaml.jinja
test.yaml.jinja
tests/default_settings/v10.0/README.md
tests/default_settings/v10.0/prod.yaml
tests/default_settings/v11.0/README.md
tests/default_settings/v11.0/prod.yaml
tests/default_settings/v12.0/README.md
tests/default_settings/v12.0/prod.yaml
tests/default_settings/v13.0/README.md
tests/default_settings/v7.0/README.md
tests/default_settings/v7.0/prod.yaml
tests/default_settings/v8.0/README.md
tests/default_settings/v8.0/prod.yaml
tests/default_settings/v9.0/README.md
tests/default_settings/v9.0/prod.yaml
tests/samples/alt-domains/prod.yaml
tests/test_default_settings.py
tests/test_nitpicking.py

Yes, I restore back the need to produce a project without pre-commit diffs. I know it won't work in all cases, but will help in most actually.
Fix a stupid blank line at the top of prod and test files.
Fix gitlab badge url: It should include the decimal part of the version.
@Tecnativa TT23300

Small improvements to templates

---

README.md
README.md.jinja
tests/default_settings/v10.0/README.md
tests/default_settings/v11.0/README.md
tests/default_settings/v12.0/README.md
tests/default_settings/v13.0/README.md
tests/default_settings/v7.0/README.md
tests/default_settings/v8.0/README.md
tests/default_settings/v9.0/README.md
tests/test_nitpicking.py

Fix readme badge

---

copier.yml
prod.yaml.jinja
test.yaml.jinja
tests/default_settings/v10.0/.copier-answers.yml
tests/default_settings/v10.0/prod.yaml
tests/default_settings/v10.0/test.yaml
tests/default_settings/v11.0/.copier-answers.yml
tests/default_settings/v11.0/prod.yaml
tests/default_settings/v11.0/test.yaml
tests/default_settings/v12.0/.copier-answers.yml
tests/default_settings/v12.0/prod.yaml
tests/default_settings/v12.0/test.yaml
tests/default_settings/v13.0/.copier-answers.yml
tests/default_settings/v13.0/prod.yaml
tests/default_settings/v13.0/test.yaml
tests/default_settings/v7.0/.copier-answers.yml
tests/default_settings/v7.0/prod.yaml
tests/default_settings/v7.0/test.yaml
tests/default_settings/v8.0/.copier-answers.yml
tests/default_settings/v8.0/prod.yaml
tests/default_settings/v8.0/test.yaml
tests/default_settings/v9.0/.copier-answers.yml
tests/default_settings/v9.0/prod.yaml
tests/default_settings/v9.0/test.yaml
tests/samples/alt-domains/prod.yaml
tests/test_default_settings.py

This is a common need, and supplied with sane defaults.
TT23300

Add paths without crawlers

---

copier.yml
prod.yaml.jinja
tasks.py
tests/default_settings/v10.0/.copier-answers.yml
tests/default_settings/v11.0/.copier-answers.yml
tests/default_settings/v12.0/.copier-answers.yml
tests/default_settings/v13.0/.copier-answers.yml
tests/default_settings/v7.0/.copier-answers.yml
tests/default_settings/v8.0/.copier-answers.yml
tests/default_settings/v9.0/.copier-answers.yml
tests/samples/cidr-whitelist/prod.yaml
tests/samples/cidr-whitelist/test.yaml
tests/test_nitpicking.py

Support CIDR whitelist

---

copier.yml
tests/default_settings/v10.0/.copier-answers.yml
tests/default_settings/v11.0/.copier-answers.yml
tests/default_settings/v12.0/.copier-answers.yml
tests/default_settings/v13.0/.copier-answers.yml
tests/default_settings/v7.0/.copier-answers.yml
tests/default_settings/v8.0/.copier-answers.yml
tests/default_settings/v9.0/.copier-answers.yml

Make AWS credentials secret

---

README.md
docs/daily-usage.md
docs/faq.md
docs/migrating-from-doodba-scaffolding.md

Moving some docs from https://github.com/Tecnativa/doodba/pull/300 and adding new ones.

Improve docs

---

.gitignore
docs/scaffolding2copier.sh
prod.yaml.jinja
tests/default_settings/v10.0/.gitignore
tests/default_settings/v10.0/prod.yaml
tests/default_settings/v11.0/.gitignore
tests/default_settings/v11.0/prod.yaml
tests/default_settings/v12.0/.gitignore
tests/default_settings/v12.0/prod.yaml
tests/default_settings/v13.0/.gitignore
tests/default_settings/v13.0/prod.yaml
tests/default_settings/v7.0/.gitignore
tests/default_settings/v7.0/prod.yaml
tests/default_settings/v8.0/.gitignore
tests/default_settings/v8.0/prod.yaml
tests/default_settings/v9.0/.gitignore
tests/default_settings/v9.0/prod.yaml
tests/samples/alt-domains/prod.yaml
tests/samples/cidr-whitelist/prod.yaml
tests/test_nitpicking.py

Users before could use that to store more secret stuff. Let them be able to continue using it as such.
Some little fixes too.

Add all .docker to .gitignore

---

copier.yml
docs/scaffolding2copier.sh
tasks_downstream.py
tests/default_settings/v10.0/tasks.py
tests/default_settings/v11.0/tasks.py
tests/default_settings/v12.0/tasks.py
tests/default_settings/v13.0/tasks.py
tests/default_settings/v7.0/tasks.py
tests/default_settings/v8.0/tasks.py
tests/default_settings/v9.0/tasks.py
tests/test_default_settings.py
tests/test_migrations.py

If this directory is not pre-created by the host user, docker will create it owned by root and we'll have permissions problems.
Fixes #36.

Autocreate odoo/auto/addons

---

tasks_downstream.py
tests/default_settings/v10.0/tasks.py
tests/default_settings/v11.0/tasks.py
tests/default_settings/v12.0/tasks.py
tests/default_settings/v13.0/tasks.py
tests/default_settings/v7.0/tasks.py
tests/default_settings/v8.0/tasks.py
tests/default_settings/v9.0/tasks.py
tests/test_nitpicking.py

Here I workaround https://github.com/microsoft/vscode/issues/95963 by making sure the private folder is second to last in the code-workspace definition.
It should make all module repos work as expected in VSCode.

Fix private location in code-workspace file

---

docs/faq.md

Also update submodule.
@Tecnativa TT23674

Improve instructions to avoid <pre> problem

---

common.yaml.jinja
docs/migrating-from-doodba-scaffolding.md
docs/scaffolding2copier.sh
prod.yaml.jinja
tests/test_settings_effect.py

Fix backup service definition
- Actually make use of `backup_deletion`.
- Choose the proper image depending on whether destination is S3.
- Validate definition using docker-compose.
@Tecnativa TT17617
---
Improve migration instructions
- Raise version to latest.
- Modify script instructions to allow using an interactive terminal, as explained in https://stackoverflow.com/a/23935690/1468388.

Backup deletion

---

.github/workflows/automerge.yml

Applies suggestion from https://github.com/pascalgn/automerge-action/issues/86#issuecomment-639408425.

Disable autorebase of PRs

---

docs/daily-usage.md
docs/faq.md

This is not our problem, but issues like #27 and #60 happen. Better add a FAQ.
Also added a handy shortcut to the daily usage development instructions, so users get up and running quicker.

Better explain db initialization

---

docs/daily-usage.md

Fixes the problem explained in https://github.com/Tecnativa/doodba-copier-template/commit/d4adfcc279c23c518d123403166601545a0822d1#r39790337.

Fix invoke instructions

---

tasks_downstream.py
tests/test_tasks_downstream.py

Also test other tasks work as expected in the same situation.

Fix resetdb execution outside of root folder

---

docs/faq.md

Answer a sensible question about pre-commit after updates

---

.github/workflows/test.yml

Docs: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#excluding-paths

Github Actions: don't run heavy tests on doc updates

---

.github/workflows/lint.yml
.github/workflows/test.yml
tasks.py

This reverts commit b600ec4f6b56b87f8c7b78c3e1497ff743e51ddc.
The tests this commit was disabling are required. I cannot set them as non-required or they wouldn't be compatible with the automerge bot. But as it is right now, I cannot merge doc-only PRs like #74.
So, after all, it less worse enabled. Reverting then.

Run all tests on docs PRs and fix CI

---

docs/daily-usage.md

See https://github.com/Tecnativa/doodba/commit/86254ae253ef11d1cc2116c1e11e533a8ea3c9f0

add --with to addons command

---

migrations.py
tests/test_migrations.py

In these cases, the update was failing. Fix migration and increase tested parameters.
@Tecnativa TT23705

Fix v2.0.0 migration when some domains answer was missing or null

---

prod.yaml.jinja
tests/samples/alt-domains/prod.yaml
tests/samples/cidr-whitelist/prod.yaml

Fix forbid crawlers in traefik 1

---

.github/workflows/test.yml
.pre-commit-config.yaml
.pre-commit-config.yaml.jinja
CONTRIBUTING.md
docs/daily-usage.md
docs/migrating-from-doodba-scaffolding.md
poetry.lock
pyproject.toml
tasks_downstream.py
tests/test_migrations.py
tests/test_nitpicking.py
tests/test_routing.py

- Merge branch 'stable'
-  Update dependencies for release. All dependencies for poetry and pre-commit are updated. Code is reformatted with latest formatters.
TT23705

Devel prepare release

---

.github/workflows/automerge.yml

Update automerge action

---

copier.yml

Support Postgres 13

---

copier.yml

Some new features for those brave souls using copier v6.0.0.a2 or later.
TT25793

Prepare for copier v6

---

common.yaml.jinja
devel.yaml.jinja
prod.yaml.jinja
test.yaml.jinja

Fixes https://github.com/Tecnativa/doodba-copier-template/issues/148

Only create postgres_db if not using external

---

common.yaml.jinja
devel.yaml.jinja
prod.yaml.jinja
test.yaml.jinja

Tiny regression from #150. I like it better as it was before (extra newline among services) for readability.

Add newline between db and previous service

---

_traefik1_labels.yml.jinja
tests/test_nitpicking.py

#157 wasn't tested and, as always happens when you don't test, was wrong. 😁
Well, now it's fixed and tested.

Complete traefik 1 domain fix

---

.github/workflows/test.yml
tasks.py
tasks.py.jinja
tests/conftest.py
tests/test_tasks_downstream.py

Add timeout to invoke start task for debugging sessions
Add option to pass --sleep argument to inv start with number of seconds
to sleep.
Use that argument in VSCode compound definition.
See https://github.com/microsoft/vscode-python/issues/14149
TT26189

Fix debugger timeout

---

README.md

Specify OS support

---

tasks_downstream.py

Arg should be "msg" instead of "message"
Just a small fix of something that should have been tested better :man_facepalming:

Fix exception call

---

tasks_downstream.py

They were hard to see.
Before: 
After:

Do not color task launchers

---

copier.yml

Avoids some unnecessary questions. Conditions are more resilient to answer content and type.

Enhance behavior with copier 6 alphas

---

tasks_downstream.py
tests/test_tasks_downstream.py

1. Map Python debugger to odoo/auto: All Odoo addons and core code are now mapped individually with the Python debugger.
2. Enable logs for test task when not in debug mode
3. Improve error messages
Error handling can still be improved, by trying to integrate better with VSCode tasks errors, but I had no success so far.
TT26728

Debugger fixes and improvements

---

.github/workflows/test.yml
odoo/Dockerfile

Try this to fix tests failing: https://github.com/Tecnativa/doodba-copier-template/runs/1442145195?check_suite_focus=true#step:13:220
Needs https://github.com/Tecnativa/doodba/pull/347

Use GitHub packages instead of docker registry

---

_traefik1_labels.yml.jinja
tests/test_routing.py

The wise man once said:
> You have a problem. You use a regexp to fix it. Now you have two problems.
Let's ~~avoid~~ fix regexes to fix #166.
BTW I update MQT repo.

Fix regex from Traefik 1 path prefix rules

---

copier.yml
migrations.py
tests/test_migrations.py

Add migration script with tests to move from settings.json to workspace file

---

README.md.jinja
copier.yml
tests/test_settings_effect.py

- Use latest image for docker-duplicity by default instead of hardcoded version
- Fix badges in README for better look

Small fixes to README and image defaults

---

.pre-commit-config.yaml.jinja

Similar to https://github.com/OCA/oca-addons-repo-template/commit/b627e7d4303d79fdd3d595fdb93a140d40fb7f5c

Add autoflake pre-commit hook

---

.eslintrc.yml.jinja
.flake8.jinja
.gitmodules
.isort.cfg.jinja
.pre-commit-config.yaml
odoo/custom/src/private/.editorconfig.jinja
tasks.py
tests/samples/mqt-diffs/v10.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v10.0-.pylintrc.diff
tests/samples/mqt-diffs/v11.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v11.0-.pylintrc.diff
tests/samples/mqt-diffs/v12.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v12.0-.pylintrc.diff
tests/samples/mqt-diffs/v13.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v13.0-.pylintrc.diff
tests/samples/mqt-diffs/v14.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v14.0-.pylintrc.diff
tests/samples/mqt-diffs/v7.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v7.0-.pylintrc.diff
tests/samples/mqt-diffs/v8.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v8.0-.pylintrc.diff
tests/samples/mqt-diffs/v9.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v9.0-.pylintrc.diff
tests/test_nitpicking.py

Avoid test errors like https://github.com/Tecnativa/doodba-copier-template/runs/2408448281?check_suite_focus=true#step:13:308

Update from oca/maintainer-quality-tools to oca/oca-addons-repo-template

---

docs/daily-usage.md

This helpful thing wasn't documented.

Advertise about preparedb usage

---

.pre-commit-config.yaml.jinja

As in https://github.com/OCA/oca-addons-repo-template/pull/58

Improve autoflake configuration

---

copier.yml
odoo/custom/build.d/{% if odoo_version < 11 %}20-update-pg-repos{% endif %}.jinja
odoo/custom/dependencies/pip.txt.jinja
tasks_downstream.py

`pathlib` is useful for insider and CI scripts.
As the images are frozen, we can add it here.
---
The official PG repos for Debian jessie have been archived: https://apt-archive.postgresql.org/
This adds the correct reference

Patch older builds

---

devel.yaml.jinja
tasks_downstream.py

This reverts commit eb8f36dbddab084bf168b51a43683cb94cfccaac
Fixes #258

Remove db filter from devel docker compose

---

common.yaml.jinja
copier.yml
tasks_downstream.py

This should avoid hitting https://github.com/copier-org/copier/issues/405 and will actually be an unsupported use case in Copier 6.

choices-same-type

---

README.md.jinja

A dash must be converted to a double dash to work.

fix: support domains with dashes

---

tasks_downstream.py

Like we do for OCA and private modules, allow to quickly `install`, `resetdb` and `test` enterprise modules.

Add enterprise module handling

---

odoo/custom/dependencies/pip.txt.jinja

Pin latest python2-compatible unidecode

---

tasks_downstream.py
tests/test_tasks_downstream.py

Add invoke tasks to easily create DB snapshots and restore them.

Add options to easily manage DB snapshots

---

common.yaml.jinja

Same problem as in https://github.com/Tecnativa/doodba-scaffolding/commit/4f8b1dc425a028237697a602cd0d09f3379ea6b7, but bigger. Increasing default value.

fix: allow bigger queries in Postgres

---

migrations.py
tests/conftest.py
tests/test_migrations.py

Parsing the yaml content and writing it again changes the yaml structure
Instead, do a plain replace in the file to avoid unnecessary changes
@Tecnativa
TT33140

Fix migration script for changing default DB_FILTER

---

devel.yaml.jinja
docs/daily-usage.md
docs/faq.md
setup-devel.yaml.jinja
tasks_downstream.py
test.yaml.jinja

No network isolation, but the rest works OK. Basic needs:
1. Aggregate code as UID=GID=0.
2. Let subuids write to `odoo/auto`.

feat: experimental podman support

---

.github/dependabot.yml
.github/workflows/dependabot-merge.yml

Auto-manage poetry and github dependencies

Enable dependabot with auto-merge

---

_macros.jinja
_traefik1_labels.yml.jinja
_traefik2_labels.yml.jinja
copier.yml
tests/test_routing.py

Allow to specifiy a 301 redirection instead of a 302 through a copier answer
@Tecnativa
TT31445

Allow different kinds of redirection in Traefik

---

_traefik2_labels.yml.jinja
copier.yml
prod.yaml.jinja

Adds two new variables:
- postgres_exposed : bool
- postgres_cidr_whitelist : multiline

Allow expose database

---

.github/workflows/test.yml
copier.yml
tests/conftest.py
tests/samples/mqt-diffs/v16.0-.pylintrc-mandatory.diff
tests/samples/mqt-diffs/v16.0-.pylintrc.diff
tests/test_routing.py
tests/test_tasks_downstream.py

- Add Python 3.10
- Add Postgres 14
TT39845

Support v16

---

copier.yml

This will make the template usable with the next Copier release.

fix: make default values match question type

---

tasks_downstream.py

fix: test task: module not in list

---

.pre-commit-config.yaml.jinja

When rendering this file, 2 lines of empty space appear.

style: remove useless leading whitespace

---

.flake8

Ignore this error because is a false positive in order to avoid pre-commit errors
CC @Tecnativa TT45846

[FIX] Ignore B023 error

---

.pre-commit-config.yaml.jinja

Improving ruff integration.
@moduon MT-4544 @EmilioPascual

feat(ruff): autofix, remove duplicate hooks

---

common.yaml.jinja
copier.yml

[IMP] Set default dockermailserver to v13.0

---

common.yaml.jinja

With the last change, updating docker-mailserver, when common.yaml is generated empty newline is generated.
CC @Tecnativa TT46621

[FIX] Fix newline auto-generated

---

_traefik3_paths_labels.yml.jinja

[FIX] Adapt redirections to Traefik 3

---

.eslintrc.yml.jinja
.github/workflows/test.yml
.pre-commit-config.yaml.jinja
copier.yml
tests/conftest.py
tests/test_tasks_downstream.py

CC @Tecnativa TT51095
- Added Odoo 18.0 option
- Added PG 16 option 
- Updated pylint version
- Fixed and temporally adjusted some tests for Odoo 18.0 because some modules are not yet migrated
- Updated oca-addons-repo-template

[ADD] Option for Odoo 18.0

---

prod.yaml.jinja
test.yaml.jinja

This follows https://github.com/odoo/odoo/pull/126808 and hardens websockets out of the box.
@moduon MT-8520

[FIX] Better bus support out of the box

---

pyproject.toml

CC @Tecnativa TT54577
This PR addresses failures in the CI pipeline due to recent updates in Poetry

[FIX] CI errors

---

.pre-commit-config.yaml.jinja

Fix https://github.com/OCA/maintainer-tools/issues/647 for doodba users.
@moduon MT-9034

fix(pre-commit): fix maintainer-tools dependencies

---

common.yaml.jinja
devel.yaml.jinja
prod.yaml.jinja
tasks_downstream.py
test.yaml.jinja
tests/test_postgres.py

Proposed by @PabloEForgeFlow 
CC @Tecnativa TT54598

[IMP] Use network alias as an alternative to db service unique name

---

common.yaml.jinja
prod.yaml.jinja
test.yaml.jinja

- DB_HOST: to allow multiple environment variables
- Remove line break after debug level on smtpreal

[FIX] Some format fixes

---

tasks_downstream.py

Closes this issue: https://github.com/Tecnativa/doodba/issues/672

[ADD] scaffold task to generate basic structure of module

---

.github/workflows/test.yml

Reduce CI job count for faster, more reliable builds.

[IMP] Reduce tests

---

.github/workflows/test.yml
.pre-commit-config.yaml.jinja
copier.yml
tasks_downstream.py
tests/conftest.py
tests/test_nitpicking.py
tests/test_tasks_downstream.py

[ADD] Odoo 19.0

---

.ruff.toml.jinja

This PR fix https://github.com/Tecnativa/doodba-copier-template/issues/568

[FIX] depracated ruff options with odoo >= 18.0
